version: "3"

services:
  notebook:
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - ~/:/app/
    command: jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token=''
